# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install semantic-release extra plugins
        run: yard add -D @semantic-release/changelog @semantic-release/git

      - name: Install node modules
        run: |
          yarn install
      - name: Run Pre-merge with Lefthook
        run: |
          yarn lefthook run pre-merge

      # - name: Run test
      #   run: |
      #     yarn test

      - name: Build
        run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
